---
- name: Just add a new user, let system select uid
  hosts: all
  become: yes

  tasks:
  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    user:
      name: janed
      comment: Jane Doe
    register: user_details

  - name: Echo user user_details
    debug:
      var: user_details