---
- name: Simple Play to add John Doe at a specific uid
  hosts: all
  # you want to send this playbook unix style hosts
  become: yes
  # need to be root to add users.

  tasks:
    - name: Remove the user 'johnd' 
      user:
        name: johnd
        state: absent
        remove: yes
